# Generated by Django 3.2.7 on 2021-10-25 23:43

from django.db import migrations, models
import user_media.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=user_media.models.upload_to_image),
        ),
    ]
