# Generated by Django 3.2.7 on 2021-11-06 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='Published')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('audios', models.ManyToManyField(related_name='note_audios', to='user_media.Audio')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_community.community')),
                ('files', models.ManyToManyField(related_name='note_files', to='user_media.File')),
                ('images', models.ManyToManyField(related_name='note_images', to='user_media.Image')),
                ('liked_by', models.ManyToManyField(related_name='note_liked_by', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='note_likes', to='user_note.Like')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(related_name='note_videos', to='user_media.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('postmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_note.postmixin')),
                ('comment_id', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Comment ID')),
            ],
            bases=('user_note.postmixin',),
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('postmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_note.postmixin')),
                ('reply_id', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Reply ID')),
                ('comment_replied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_replied', to='user_note.comment')),
            ],
            bases=('user_note.postmixin',),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('postmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_note.postmixin')),
                ('reposts_amount', models.PositiveIntegerField(blank=True, default=0, verbose_name='Reposts')),
                ('note_id', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Note ID')),
                ('comments', models.ManyToManyField(related_name='note_comments', to='user_note.Comment')),
            ],
            bases=('user_note.postmixin',),
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_to_comment', to='user_note.comment'),
        ),
        migrations.AddField(
            model_name='like',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_to_note', to='user_note.note'),
        ),
        migrations.AddField(
            model_name='like',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_to_reply', to='user_note.reply'),
        ),
        migrations.AddField(
            model_name='comment',
            name='note_commented',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_note', to='user_note.note'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(related_name='comment_replies', to='user_note.Reply'),
        ),
    ]
