# Generated by Django 3.2.7 on 2021-10-18 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMixin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='Published')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('likes_amount', models.PositiveIntegerField(blank=True, default=0, verbose_name='Likes')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_community.community')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('postmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_note.postmixin')),
                ('comments_amount', models.PositiveIntegerField(blank=True, default=0, verbose_name='Comments')),
                ('reposts_amount', models.PositiveIntegerField(blank=True, default=0, verbose_name='Reposts')),
            ],
            bases=('user_note.postmixin', models.Model),
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteVideo',
            fields=[
                ('video_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_media.video')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_note.note')),
            ],
            bases=('user_media.video', models.Model),
        ),
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_media.image')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_note.note')),
            ],
            bases=('user_media.image', models.Model),
        ),
        migrations.CreateModel(
            name='NoteFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_media.file')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_note.note')),
            ],
            bases=('user_media.file', models.Model),
        ),
        migrations.CreateModel(
            name='NoteAudio',
            fields=[
                ('audio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_media.audio')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_note.note')),
            ],
            bases=('user_media.audio', models.Model),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('postmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_note.postmixin')),
                ('replies_amount', models.PositiveIntegerField()),
                ('replies_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_note.comment')),
            ],
            bases=('user_note.postmixin', models.Model),
        ),
    ]
