# Generated by Django 3.2.7 on 2021-10-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Comment ID'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_id',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Note ID'),
        ),
    ]
