# Generated by Django 3.2.7 on 2021-11-04 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_note', '0002_auto_20211104_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_to_reply', to='user_note.reply'),
        ),
    ]
