# Generated by Django 3.2.7 on 2021-10-30 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_media', '0001_initial'),
        ('user_note', '0002_auto_20211030_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='audios',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='files',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='images',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='replies_to',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='note',
            name='audios',
        ),
        migrations.RemoveField(
            model_name='note',
            name='files',
        ),
        migrations.RemoveField(
            model_name='note',
            name='images',
        ),
        migrations.RemoveField(
            model_name='note',
            name='videos',
        ),
        migrations.AddField(
            model_name='note',
            name='comments',
            field=models.ManyToManyField(related_name='note_comments', to='user_note.Comment'),
        ),
        migrations.AddField(
            model_name='postmixin',
            name='audios',
            field=models.ManyToManyField(related_name='comment_audios', to='user_media.Audio'),
        ),
        migrations.AddField(
            model_name='postmixin',
            name='files',
            field=models.ManyToManyField(related_name='comment_files', to='user_media.File'),
        ),
        migrations.AddField(
            model_name='postmixin',
            name='images',
            field=models.ManyToManyField(related_name='comment_images', to='user_media.Image'),
        ),
        migrations.AddField(
            model_name='postmixin',
            name='videos',
            field=models.ManyToManyField(related_name='comment_videos', to='user_media.Video'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_note.comment')),
                ('reply_id', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Reply ID')),
                ('replies_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply_source', to='user_note.comment')),
            ],
            bases=('user_note.comment',),
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(related_name='comment_replies', to='user_note.Reply'),
        ),
    ]
