# Generated by Django 3.2.7 on 2021-11-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_media', '0001_initial'),
        ('user_note', '0003_auto_20211030_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmixin',
            name='likes',
            field=models.ManyToManyField(related_name='note_likes', to='user_note.Like'),
        ),
        migrations.AlterField(
            model_name='postmixin',
            name='audios',
            field=models.ManyToManyField(related_name='note_audios', to='user_media.Audio'),
        ),
        migrations.AlterField(
            model_name='postmixin',
            name='files',
            field=models.ManyToManyField(related_name='note_files', to='user_media.File'),
        ),
        migrations.AlterField(
            model_name='postmixin',
            name='images',
            field=models.ManyToManyField(related_name='note_images', to='user_media.Image'),
        ),
        migrations.AlterField(
            model_name='postmixin',
            name='likes_amount',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Likes_amount'),
        ),
        migrations.AlterField(
            model_name='postmixin',
            name='videos',
            field=models.ManyToManyField(related_name='note_videos', to='user_media.Video'),
        ),
    ]
