# Generated by Django 3.2.7 on 2021-11-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_note', '0005_auto_20211102_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replies_amount',
        ),
        migrations.RemoveField(
            model_name='note',
            name='comments_amount',
        ),
        migrations.RemoveField(
            model_name='postmixin',
            name='likes_amount',
        ),
    ]
