# Generated by Django 3.2.7 on 2021-11-02 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_note', '0006_auto_20211102_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmixin',
            name='liked_by',
            field=models.ManyToManyField(related_name='note_liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
