# Generated by Django 3.2.7 on 2021-11-03 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_note', '0007_postmixin_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='note_commented',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commented_note', to='user_note.note'),
        ),
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_to_comment', to='user_note.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_to_note', to='user_note.note'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='replies_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_source', to='user_note.comment'),
        ),
    ]
