# Generated by Django 3.2.7 on 2021-11-06 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_community', '0001_initial'),
        ('user_note', '0001_initial'),
        ('user_media', '0001_initial'),
        ('user_chat', '0001_initial'),
        ('user', '0001_initial'),
        ('user_friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='audios',
            field=models.ManyToManyField(related_name='user_audios', to='user_media.Audio'),
        ),
        migrations.AddField(
            model_name='user',
            name='community_subscribes',
            field=models.ManyToManyField(related_name='community_subscribes_list', through='user_community.CommunitySubscriber', to='user_community.Community'),
        ),
        migrations.AddField(
            model_name='user',
            name='files',
            field=models.ManyToManyField(related_name='user_files', to='user_media.File'),
        ),
        migrations.AddField(
            model_name='user',
            name='friend_requests',
            field=models.ManyToManyField(related_name='friend_requests', to='user_friend.UserFriendRequest'),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='friend_list', through='user_friend.Friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='group_chats',
            field=models.ManyToManyField(related_name='user_group_chats', to='user_chat.GroupChat'),
        ),
        migrations.AddField(
            model_name='user',
            name='images',
            field=models.ManyToManyField(related_name='user_images', to='user_media.Image'),
        ),
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.ManyToManyField(related_name='user_notes', to='user_note.Note'),
        ),
        migrations.AddField(
            model_name='user',
            name='private_chats',
            field=models.ManyToManyField(related_name='user_private_chats', to='user_chat.PrivateChat'),
        ),
        migrations.AddField(
            model_name='user',
            name='reposts',
            field=models.ManyToManyField(related_name='user_reposts', to='user_note.Note'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_subscribes',
            field=models.ManyToManyField(related_name='user_subscribes_list', through='user_friend.Subscribe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='videos',
            field=models.ManyToManyField(related_name='user_videos', to='user_media.Video'),
        ),
    ]
