# Generated by Django 3.2.7 on 2021-10-18 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('user_community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscribed_to_community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_subscriber', to='user_community.community'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscribed_to_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriber', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='community_subscribes',
            field=models.ManyToManyField(related_name='user_subscribers', through='user.Subscriber', to='user_community.Community'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_subscribes',
            field=models.ManyToManyField(related_name='user_subscribers', through='user.Subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
