# Generated by Django 3.2.7 on 2021-10-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat', '0003_auto_20211026_0243'),
        ('user', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_chats',
            field=models.ManyToManyField(related_name='user_group_chats', to='user_chat.GroupChat'),
        ),
        migrations.AddField(
            model_name='user',
            name='private_chats',
            field=models.ManyToManyField(related_name='user_private_chats', to='user_chat.PrivateChat'),
        ),
    ]
