# Generated by Django 3.2.7 on 2021-11-22 16:19

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/icons/user_icon.png', upload_to=user.models.upload_to_profile_picture),
        ),
    ]
