# Generated by Django 3.2.7 on 2021-10-18 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_community', '0002_communitysubscriber'),
        ('user', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='subscribed_to_community',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscriber',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to='user.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscribed_to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='community_subscribes',
            field=models.ManyToManyField(related_name='community_subscribes', through='user_community.CommunitySubscriber', to='user_community.Community'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_subscribes',
            field=models.ManyToManyField(related_name='followers', through='user.Subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
