# Generated by Django 3.2.7 on 2021-10-20 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_friend', '0001_initial'),
        ('user', '0003_auto_20211019_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_requests',
            field=models.ManyToManyField(related_name='friend_requests', to='user_friend.UserFriendRequest'),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_user_friends_+', through='user_friend.Friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_subscribes',
            field=models.ManyToManyField(related_name='followers', through='user_friend.Subscribe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
