# Generated by Django 3.2.7 on 2021-10-21 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_friend', '0002_rename_status_userfriendrequest_state'),
        ('user_community', '0003_auto_20211021_2050'),
        ('user', '0004_auto_20211020_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='community_subscribes',
            field=models.ManyToManyField(related_name='community_subscribes_list', through='user_community.CommunitySubscriber', to='user_community.Community'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_subscribes',
            field=models.ManyToManyField(related_name='user_subscribes_list', through='user_friend.Subscribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
