# Generated by Django 3.2.7 on 2021-10-18 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_id', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Community ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('is_public', models.BooleanField(choices=[(True, 'Public'), (False, 'Private')], default=False, verbose_name='Private or Public community')),
                ('website', models.URLField(blank=True, default=None, null=True, verbose_name='Website')),
                ('about', models.TextField(blank=True, default=None, max_length=32767, null=True, verbose_name='About me')),
                ('subscribers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
