# Generated by Django 3.2.7 on 2021-10-18 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_to_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='user_community.community')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_community', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
