# Generated by Django 3.2.7 on 2021-11-22 16:19

from django.db import migrations, models
import user_community.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_community', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='preview_picture',
            field=models.ImageField(blank=True, default='static/icons/user_icon.png', upload_to=user_community.models.upload_to_community_picture),
        ),
    ]
