# Generated by Django 3.2.7 on 2021-10-21 17:50

from django.conf import settings
from django.db import migrations, models
import user_community.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_community', '0002_communitysubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='community',
            name='facebook',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='community',
            name='instagram',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='community',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='community',
            name='preview_pictrue',
            field=models.ImageField(blank=True, upload_to=user_community.models.upload_to_community_picture),
        ),
        migrations.AddField(
            model_name='community',
            name='staff_list',
            field=models.ManyToManyField(related_name='staff_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='twitter',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='community',
            name='vk',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='VK'),
        ),
    ]
