# Generated by Django 3.2.7 on 2021-10-21 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_community', '0003_auto_20211021_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='preview_pictrue',
            new_name='preview_picture',
        ),
        migrations.RenameField(
            model_name='communitysubscriber',
            old_name='subscriber',
            new_name='from_user',
        ),
        migrations.RemoveField(
            model_name='communitysubscriber',
            name='subscribed_to_community',
        ),
        migrations.AddField(
            model_name='community',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Community name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communitysubscriber',
            name='to_community',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='followed', to='user_community.community'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CommunitySubscribeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(choices=[(None, 'Await'), (True, 'Accepted'), (False, 'Rejected')], default=None, max_length=25, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_request_from', to=settings.AUTH_USER_MODEL)),
                ('to_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_request_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='subscribe_requests',
            field=models.ManyToManyField(related_name='subscribe_requests', to='user_community.CommunitySubscribeRequest'),
        ),
    ]
