# Generated by Django 3.2.7 on 2021-10-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_community', '0004_auto_20211022_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='is_public',
            field=models.BooleanField(choices=[(True, 'Public'), (False, 'Private')], default=True, verbose_name='Private or Public community'),
        ),
    ]
