# Generated by Django 3.2.7 on 2021-10-29 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_chat.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to=user_chat.models.upload_to_picture)),
                ('name', models.CharField(max_length=255, verbose_name='Chat name')),
                ('chat_id', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Chat ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='Published')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('message_id', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Message ID')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Chat ID')),
                ('member_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_member_1', to=settings.AUTH_USER_MODEL)),
                ('member_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_member_2', to=settings.AUTH_USER_MODEL)),
                ('messages', models.ManyToManyField(related_name='private_chat_messages', to='user_chat.Message')),
            ],
        ),
    ]
