# Generated by Django 3.2.7 on 2021-10-25 23:43

from django.conf import settings
from django.db import migrations, models
import user_chat.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='chat_id',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Chat ID'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Chat name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupchat',
            name='picture',
            field=models.ImageField(blank=True, upload_to=user_chat.models.upload_to_picture),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='staff',
            field=models.ManyToManyField(related_name='group_chat_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='chat_id',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Chat ID'),
        ),
    ]
