# Generated by Django 3.2.7 on 2021-11-22 16:19

from django.db import migrations, models
import user_chat.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='picture',
            field=models.ImageField(blank=True, default='static/icons/user_icon.png', upload_to=user_chat.models.upload_to_picture),
        ),
    ]
